# Shows how the r-build-check.yml can be called from another repository.
name: r-build-check
on:
    push:
        branches: ['main']
    workflow_dispatch:
jobs:
    build-check:
        uses: FertigLab/actions/.github/workflows/r-build-check.yml@v1
